### ISSUE TITLE
bazel issue

### ISSUE THREAD

**Issue by rahul-nitkkr** [rahul-nitkkr/test#1]
What we are doing :
Want to build java/scala without needing to have source code on disk
We are dumping all BUILD files of individual projects within our monorepo and the WORKSPACE file at the root, which in theory should allow us to build the Action graph
We plan to leverage remote execution/caching to scale the builds.

We have a CAS available within the organization , which we are planning to leverage to serve content and digests to bazel
Patching BazelFileSystemModule to serve our custom FS implementation which interfaces with the CAS allows us to do so, and serves up the Digests when requested for a particular path
Involved overriding readdir/getDirectoryEntries to serve up the Dirents as well.

When running in remote mode , I’d have assumed the below workflow :
1)	The local bazel client builds the action graph reading the build files and interfacing with CustomFileSystemService to get digests for various paths within a build action
2)	Then computes the input tree and Action to be performed
3)	Then it does GetActionResult to the remote server with the Action digest to figure out if the results are already present in the ActionCache
4)	Then queries the CAS to find missing blobs [ in our case this almost always returns true ] < Footnote for more detail >
5)	Then 
```
SUBCOMMAND: # //jsi-annotations:jsi_jsi_annotations_main [action 'Building jsi-annotations/libjsi_jsi_annotations_main.jar ()']
(cd /local/data/scratch/.cache/bazel/_bazel_p2dpgnp/b6669dedfcd2eab0c289aa50224e42cf/execroot/jsi_root && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  external/embedded_jdk/bin/java -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -Xbootclasspath/p:/sw/external/jdk-1.8.0_60_x64/jre/lib/tools.jar -jar external/bazel_tools/tools/jdk/VanillaJavaBuilder_deploy.jar @bazel-out/k8-fastbuild/bin/jsi-annotations/libjsi_jsi_annotations_main.jar-0.params)
ERROR: /local/data/scratch/royrah2/bazel10/jsi-annotations/BUILD:43:1: Couldn't build file jsi-annotations/libjsi_jsi_annotations_main.jar: Building jsi-annotations/libjsi_jsi_annotations_main.jar () failed (Exit 34). Note: Remote connection/protocol failed with: execution failed Call failed after 5 retry attempts: io.grpc.StatusRuntimeException: INTERNAL: Half-closed without a request
ARTIFACT annotations/src/com/gs/annotation/package-info.java
ARTIFACT annotations/src/com/gs/annotation/package-info.java
ARTIFACT annotations/src/com/gs/annotation/NotThreadSafe.java
ARTIFACT -annotations/src/com/gs/annotation/NotThreadSafe.java
ARTIFACT jsi-annotations/src/com/gs/annotation/NonNull.java
ARTIFACT jsi-annotations/src/com/gs/annotation/NonNull.java
ARTIFACT jsi-annotations/src/com/gs/annotation/Nullable.java
ARTIFACT jsi-annotations/src/com/gs/annotation/Nullable.java
ARTIFACT jsi-annotations/src/com/gs/annotation/Immutable.java
ARTIFACT jsi-annotations/src/com/gs/annotation/Immutable.java
ARTIFACT jsi-annotations/src/com/gs/annotation/ThreadSafe.java
ARTIFACT jsi-annotations/src/com/gs/annotation/ThreadSafe.java
ARTIFACT jsi-annotations/src/com/gs/annotation/GuardedBy.java
ARTIFACT jsi-annotations/src/com/gs/annotation/GuardedBy.java
ARTIFACT jsi-annotations/src/com/gs/annotation/Stateless.java
ARTIFACT jsi-annotations/src/com/gs/annotation/Stateless.java
SUBCOMMAND: # //jsi-annotations:jsi_jsi_annotations_java_main [action 'Building jsi-annotations/libjsi_jsi_annotations_java_main.jar (8 source files)']
(cd /local/data/scratch/.cache/bazel/_bazel_p2dpgnp/b6669dedfcd2eab0c289aa50224e42cf/execroot/jsi_root && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  external/embedded_jdk/bin/java -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -Xbootclasspath/p:/sw/external/jdk-1.8.0_60_x64/jre/lib/tools.jar -jar external/bazel_tools/tools/jdk/VanillaJavaBuilder_deploy.jar @bazel-out/k8-fastbuild/bin/jsi-annotations/libjsi_jsi_annotations_java_main.jar-0.params)
ERROR: /local/data/scratch/royrah2/bazel10/jsi-annotations/BUILD:15:1: Couldn't build file jsi-annotations/libjsi_jsi_annotations_java_main.jar: Building jsi-annotations/libjsi_jsi_annotations_java_main.jar (8 source files) failed (Exit 34). Note: Remote connection/protocol failed with: execution failed Call failed after 5 retry attempts: io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
Target //jsi-annotations:jsi_jsi_annotations_main failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

SUBCOMMAND: # //jsi-annotations:jsi_jsi_annotations_java_main [action 'Building jsi-annotations/libjsi_jsi_annotations_java_main.jar (8 source files)']
(cd /local/data/scratch/.cache/bazel/_bazel_p2dpgnp/b6669dedfcd2eab0c289aa50224e42cf/execroot/jsi_root && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  external/embedded_jdk/bin/java -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -Xbootclasspath/p:/sw/external/jdk-1.8.0_60_x64/jre/lib/tools.jar -jar external/bazel_tools/tools/jdk/VanillaJavaBuilder_deploy.jar @bazel-out/k8-fastbuild/bin/jsi-annotations/libjsi_jsi_annotations_java_main.jar-0.params)
ERROR: /local/data/scratch/royrah2/bazel10/jsi-annotations/BUILD:15:1: Couldn't build file jsi-annotations/libjsi_jsi_annotations_java_main.jar: Building jsi-annotations/libjsi_jsi_annotations_java_main.jar (8 source files) failed (Exit 1)
jsi-annotations/src/com/gs/annotation/GuardedBy.java: error: error reading jsi-annotations/src/com/gs/annotation/GuardedBy.java; jsi-annotations/src/com/gs/annotation/GuardedBy.java (No such file or directory)
jsi-annotations/src/com/gs/annotation/Immutable.java: error: error reading jsi-annotations/src/com/gs/annotation/Immutable.java; jsi-annotations/src/com/gs/annotation/Immutable.java (No such file or directory)
jsi-annotations/src/com/gs/annotation/NonNull.java: error: error reading jsi-annotations/src/com/gs/annotation/NonNull.java; jsi-annotations/src/com/gs/annotation/NonNull.java (No such file or directory)
jsi-annotations/src/com/gs/annotation/NotThreadSafe.java: error: error reading jsi-annotations/src/com/gs/annotation/NotThreadSafe.java; jsi-annotations/src/com/gs/annotation/NotThreadSafe.java (No such file or directory)
jsi-annotations/src/com/gs/annotation/Nullable.java: error: error reading jsi-annotations/src/com/gs/annotation/Nullable.java; jsi-annotations/src/com/gs/annotation/Nullable.java (No such file or directory)
jsi-annotations/src/com/gs/annotation/Stateless.java: error: error reading jsi-annotations/src/com/gs/annotation/Stateless.java; jsi-annotations/src/com/gs/annotation/Stateless.java (No such file or directory)
jsi-annotations/src/com/gs/annotation/ThreadSafe.java: error: error reading jsi-annotations/src/com/gs/annotation/ThreadSafe.java; jsi-annotations/src/com/gs/annotation/ThreadSafe.java (No such file or directory)
jsi-annotations/src/com/gs/annotation/package-info.java: error: error reading jsi-annotations/src/com/gs/annotation/package-info.java; jsi-annotations/src/com/gs/annotation/package-info.java (No such file or directory)
Target //jsi-annotations:jsi_jsi_annotations_main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.522s, Critical Path: 0.31s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 1 process: 1 worker.
FAILED: Build did NOT complete successfully
[

06:46:07.954 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] INBOUND DATA: streamId=13 padding=0 endStream=true length=51 bytes=000000002e122c0a2839313237346665376636643532663733663266313836663465373038643833636233633339663766105d
06:46:07.955 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] OUTBOUND HEADERS: streamId=13 headers=GrpcHttp2OutboundHeaders[:status: 200, content-type: application/grpc, grpc-status: 13, grpc-message: Half-closed without a request] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
06:46:07.955 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] OUTBOUND RST_STREAM: streamId=13 errorCode=8
06:46:07.957 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] INBOUND RST_STREAM: streamId=13 errorCode=8
06:46:08.100 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] INBOUND HEADERS: streamId=15 headers=GrpcHttp2RequestHeaders[:path: /build.bazel.remote.execution.v2.ActionCache/GetActionResult, :authority: localhost:8980, :method: POST, :scheme: http, te: trailers, content-type: application/grpc, user-agent: grpc-java-netty/1.10.0, build.bazel.remote.execution.v2.requestmetadata-bin: ChsKBWJhemVsEhIwLjE5LjAtIChAbm9uLWdpdCkSKGEyZGZkNjg0YWU4NGRiMjBlMTMzZDM1ZjFlZjVkZDk5MTQ3OTIwYjcaJGMxY2ZhZGU1LTUyYzgtNGRkOS05M2JiLWIwNDMwN2I4ZTdmYSIkZjAxMjU1MGQtNjU2Mi00ZTQwLTk4YWMtZTdlMmEwZmNiZWY3, grpc-accept-encoding: gzip, grpc-timeout: 59999912u, grpc-trace-bin: ] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
06:46:08.100 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] INBOUND DATA: streamId=15 padding=0 endStream=true length=51 bytes=000000002e122c0a2861326466643638346165383464623230653133336433356631656635646439393134373932306237105e
06:46:08.101 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] OUTBOUND RST_STREAM: streamId=15 errorCode=8
06:46:08.106 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] INBOUND RST_STREAM: streamId=15 errorCode=8

**Comment by rahul-nitkkr** [comment]
06:46:07.954 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] INBOUND DATA: streamId=13 padding=0 endStream=true length=51 bytes=000000002e122c0a2839313237346665376636643532663733663266313836663465373038643833636233633339663766105d
06:46:07.955 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] OUTBOUND HEADERS: streamId=13 headers=GrpcHttp2OutboundHeaders[:status: 200, content-type: application/grpc, grpc-status: 13, grpc-message: Half-closed without a request] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
06:46:07.955 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] OUTBOUND RST_STREAM: streamId=13 errorCode=8
06:46:07.957 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] INBOUND RST_STREAM: streamId=13 errorCode=8
06:46:08.100 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] INBOUND HEADERS: streamId=15 headers=GrpcHttp2RequestHeaders[:path: /build.bazel.remote.execution.v2.ActionCache/GetActionResult, :authority: localhost:8980, :method: POST, :scheme: http, te: trailers, content-type: application/grpc, user-agent: grpc-java-netty/1.10.0, build.bazel.remote.execution.v2.requestmetadata-bin: ChsKBWJhemVsEhIwLjE5LjAtIChAbm9uLWdpdCkSKGEyZGZkNjg0YWU4NGRiMjBlMTMzZDM1ZjFlZjVkZDk5MTQ3OTIwYjcaJGMxY2ZhZGU1LTUyYzgtNGRkOS05M2JiLWIwNDMwN2I4ZTdmYSIkZjAxMjU1MGQtNjU2Mi00ZTQwLTk4YWMtZTdlMmEwZmNiZWY3, grpc-accept-encoding: gzip, grpc-timeout: 59999912u, grpc-trace-bin: ] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
06:46:08.100 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] INBOUND DATA: streamId=15 padding=0 endStream=true length=51 bytes=000000002e122c0a2861326466643638346165383464623230653133336433356631656635646439393134373932306237105e
06:46:08.101 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] OUTBOUND RST_STREAM: streamId=15 errorCode=8
06:46:08.106 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaae9acd6, L:/127.0.0.1:8980 - R:/127.0.0.1:49649] INBOUND RST_STREAM: streamId=15 errorCode=8

**Comment by rahul-nitkkr** [comment]
```
SUBCOMMAND: # //my-annotations:my_my_annotations_main [action 'Building my-annotations/libmy_my_annotations_main.jar ()']
(cd /local/data/scratch/.cache/bazel/_bazel_p2dpgnp/b6669dedfcd2eab0c289aa50224e42cf/execroot/my_root && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  external/embedded_jdk/bin/java -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -Xbootclasspath/p:/sw/external/jdk-1.8.0_60_x64/jre/lib/tools.jar -jar external/bazel_tools/tools/jdk/VanillaJavaBuilder_deploy.jar @bazel-out/k8-fastbuild/bin/my-annotations/libmy_my_annotations_main.jar-0.params)
ERROR: /local/data/scratch/royrah2/bazel10/my-annotations/BUILD:43:1: Couldn't build file my-annotations/libmy_my_annotations_main.jar: Building my-annotations/libmy_my_annotations_main.jar () failed (Exit 34). Note: Remote connection/protocol failed with: execution failed Call failed after 5 retry attempts: io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream: com.google.devtools.build.lib.remote.Retrier$RetryException: Call failed after 5 retry attempts: io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
        at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:290)
        at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:121)
        at com.google.devtools.build.lib.remote.GrpcRemoteCache.getCachedActionResult(GrpcRemoteCache.java:373)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:174)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:106)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:75)
        at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:288)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:295)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:1001)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:930)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:121)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:770)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:725)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:478)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:519)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:216)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131)
        at build.bazel.remote.execution.v2.ActionCacheGrpc$ActionCacheBlockingStub.getActionResult(ActionCacheGrpc.java:347)
        at com.google.devtools.build.lib.remote.GrpcRemoteCache.lambda$getCachedActionResult$2(GrpcRemoteCache.java:376)
        at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:268)
        ... 22 more
SUBCOMMAND: # //my-annotations:my_my_annotations_java_main [action 'Building my-annotations/libmy_my_annotations_java_main.jar (8 source files)']
(cd /local/data/scratch/.cache/bazel/_bazel_p2dpgnp/b6669dedfcd2eab0c289aa50224e42cf/execroot/my_root && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  external/embedded_jdk/bin/java -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -Xbootclasspath/p:/sw/external/jdk-1.8.0_60_x64/jre/lib/tools.jar -jar external/bazel_tools/tools/jdk/VanillaJavaBuilder_deploy.jar @bazel-out/k8-fastbuild/bin/my-annotations/libmy_my_annotations_java_main.jar-0.params)
ERROR: /local/data/scratch/royrah2/bazel10/my-annotations/BUILD:15:1: Couldn't build file my-annotations/libmy_my_annotations_java_main.jar: Building my-annotations/libmy_my_annotations_java_main.jar (8 source files) failed (Exit 34). Note: Remote connection/protocol failed with: execution failed Call failed after 5 retry attempts: io.grpc.StatusRuntimeException: INTERNAL: Half-closed without a request: com.google.devtools.build.lib.remote.Retrier$RetryException: Call failed after 5 retry attempts: io.grpc.StatusRuntimeException: INTERNAL: Half-closed without a request
        at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:290)
        at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:121)
        at com.google.devtools.build.lib.remote.GrpcRemoteCache.getCachedActionResult(GrpcRemoteCache.java:373)
        at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:174)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:106)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:75)
        at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:288)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:295)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:1001)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:930)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:121)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:770)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:725)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:478)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:519)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:216)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Half-closed without a request
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131)
        at build.bazel.remote.execution.v2.ActionCacheGrpc$ActionCacheBlockingStub.getActionResult(ActionCacheGrpc.java:347)
        at com.google.devtools.build.lib.remote.GrpcRemoteCache.lambda$getCachedActionResult$2(GrpcRemoteCache.java:376)
        at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:268)
        ... 22 more
Target //my-annotations:my_my_annotations_main failed to build
INFO: Elapsed time: 7.022s, Critical Path: 3.24s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 0 processes.
FAILED: Build did NOT complete successfully

```
